package com.betterwhips.client;

import com.betterwhips.client.AmethystWhipHitEffects;
import com.betterwhips.client.AmethystWhipPhysics;
import com.betterwhips.client.AmethystWhipProjectileEffects;
import com.betterwhips.client.ChainWhipHitEffects;
import com.betterwhips.client.ChainWhipPhysics;
import com.betterwhips.client.DestructionWhipHitEffects;
import com.betterwhips.client.DestructionWhipPhysics;
import com.betterwhips.client.DiamondBladeWhipHitEffects;
import com.betterwhips.client.DiamondBladeWhipPhysics;
import com.betterwhips.client.EmeraldWhipHitEffects;
import com.betterwhips.client.EmeraldWhipPhysics;
import com.betterwhips.client.EmeraldWhipProjectileEffects;
import com.betterwhips.client.GoldenHeavyWhipHitEffects;
import com.betterwhips.client.GoldenHeavyWhipPhysics;
import com.betterwhips.client.LeatherWhipHitEffects;
import com.betterwhips.client.LightningWhipHitEffects;
import com.betterwhips.client.LeatherWhipPhysics;
import com.betterwhips.client.LightningWhipPhysics;
import com.betterwhips.client.RoyalSlimeWhipHitEffects;
import com.betterwhips.client.RoyalSlimeWhipHudOverlay;
import com.betterwhips.client.RoyalSlimeWhipPhysics;
import com.betterwhips.client.SeaRippleWhipPhysics;
import com.betterwhips.client.TrainerWhipPhysics;
import com.betterwhips.client.WhipShockwaveEffects;
import com.betterwhips.client.WindwhispererWhipPhysics;
import net.neoforged.api.distmarker.Dist;
import net.minecraftforge.eventbus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.minecraftforge.common.MinecraftForge;

@Mod(value="better_whips", dist={Dist.CLIENT})
public final class BetterWhipsClient {
    public BetterWhipsClient(IEventBus modBus) {
        modBus.addListener(RoyalSlimeWhipHudOverlay::registerShaders);
        modBus.addListener(LightningWhipVfx::registerShaders);
        modBus.addListener(SeaRippleWhipVfx::registerShaders);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipHudOverlay::onLogout);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipHudOverlay::onRenderGuiLayer);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipHitEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipHitEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(RoyalSlimeWhipHitEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(LeatherWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(LightningWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(LeatherWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(LightningWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(LeatherWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(LightningWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(LeatherWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(LightningWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(LeatherWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(LightningWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(LeatherWhipHitEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(LightningWhipHitEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(LeatherWhipHitEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(LightningWhipHitEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(LeatherWhipHitEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(LightningWhipHitEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(TrainerWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(TrainerWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(TrainerWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(TrainerWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(TrainerWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(SeaRippleWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(SeaRippleWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(SeaRippleWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(SeaRippleWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(SeaRippleWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(SeaRippleWhipEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(SeaRippleWhipHud::onRenderGuiLayer);
        MinecraftForge.EVENT_BUS.addListener(ChainWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(ChainWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(ChainWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(ChainWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(ChainWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(ChainWhipHitEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(ChainWhipHitEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(ChainWhipHitEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(GoldenHeavyWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(GoldenHeavyWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(GoldenHeavyWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(GoldenHeavyWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(GoldenHeavyWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(GoldenHeavyWhipHitEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(GoldenHeavyWhipHitEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(GoldenHeavyWhipHitEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(DiamondBladeWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(DiamondBladeWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(DiamondBladeWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(DiamondBladeWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(DiamondBladeWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(DiamondBladeWhipHitEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(DiamondBladeWhipHitEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(DiamondBladeWhipHitEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipHitEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipHitEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipHitEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipProjectileEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipProjectileEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(EmeraldWhipProjectileEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipHitEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipHitEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipHitEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipProjectileEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipProjectileEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(AmethystWhipProjectileEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(DestructionWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(DestructionWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(DestructionWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(DestructionWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(DestructionWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(DestructionWhipHitEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(DestructionWhipHitEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(DestructionWhipHitEffects::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(WindwhispererWhipPhysics::onInteractionKey);
        MinecraftForge.EVENT_BUS.addListener(WindwhispererWhipPhysics::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(WindwhispererWhipPhysics::onLogout);
        MinecraftForge.EVENT_BUS.addListener(WindwhispererWhipPhysics::onRenderLevel);
        MinecraftForge.EVENT_BUS.addListener(WindwhispererWhipPhysics::onRenderArm);
        MinecraftForge.EVENT_BUS.addListener(WhipShockwaveEffects::onClientTick);
        MinecraftForge.EVENT_BUS.addListener(WhipShockwaveEffects::onLogout);
        MinecraftForge.EVENT_BUS.addListener(WhipShockwaveEffects::onRenderLevel);
    }
}
